### ISSUE TITLE
Q: How do I refresh the forge client so that deleted issues are removed locally

### ISSUE THREAD

**Issue by rileyrg** [magit/forge#252] opened 2020-03-04 22:56 UTC
I deleted an issue on the github server but it wont go away on my client. I did a forge fetch all but the issue remains.

**Comment by tarsius** [comment] 2020-03-04 23:06
The api does not answer the question "what topics have been deleted" so we would have to ask "this is a list of all issues, which one of those do not exist anymore". The latter would be very cumbersome and costly so we don't do it.

Duplicate of #163.

**Closed by tarsius** 2020-03-04 23:06 UTC
Labels: duplicate

**Comment by rileyrg** [comment] 2020-03-04 23:47
fair enough. Wonderful module. I just did a database reset - learning by
doing.

**Comment by tarsius** [comment] 2020-03-04 23:48
There's also `forge-remove-topic-locally`.

**Comment by rileyrg** [comment] 2020-03-04 23:51
Oh wonderful. I missed that.  Thank you.
