### ISSUE TITLE
[GitHub] Transferred issues are not removed from forge database

### ISSUE THREAD

**Issue by christopher-dG** [magit/forge#271] opened 2020-04-29 21:00 UTC
On GitHub, if you create an issue, pull it with forge, transfer the issue to another repository, then pull again with forge, the issue remains visible. `magit-browse-thing` actually works because GH handles the redirect, but attempting to comment on the issue via forge results in a 404.

**Comment by tarsius** [comment] 2020-04-29 21:13
Duplicate of #252 and #163.

**Closed** 2020-04-29 21:14 UTC
Labels: duplicate

**Comment by christopher-dG** [comment] 2020-04-29 21:17
Thanks for pointing me to `forge-remove-topic-locally`, sorry for the noise.

**Comment by tarsius** [comment] 2020-04-29 21:19
I've just added https://github.com/magit/forge/wiki/FAQ :stuck_out_tongue:
