### ISSUE TITLE
Deleted issues continue to show up

### ISSUE THREAD

**Issue by coolsidd** [magit/forge#163] opened 2019-06-15 20:19 UTC
I deleted an issue on my GitHub repo, however, it still shows up in forge. Can you replicate/confirm this?

**Comment by tarsius** [comment] 2019-06-15 20:58
That's intended and if you don't like it, then you can `(setcdr forge-topic-list-limit 0)`.

Duplicate of #141.

**Closed by tarsius** 2019-06-15 20:58 UTC
Labels: support

**Comment by coolsidd** [comment] 2019-06-16 18:46
I don't think you understand. I mean "deleted" not "closed". I am fine with closed/greyed out issues appearing, I am talking about deleting an issue like [here]( https://help.github.com/en/articles/deleting-an-issue)

**Comment by tarsius** [comment] 2019-06-16 18:53
The way we fetch issues I don't think we can detect when an issue was deleted. Currently we fetch all issues that were modified since we last fetched--deleted issues don't show up in that list. Could be fairly expensive to check for deleted issues and a lot of work to implement it, so this is not a high priority.

**Comment by tarsius** [comment] 2019-06-16 18:53
Same for issues that were migrated away. And pull-requests of course.
