### ISSUE TITLE
can't open PR after repo switches GHE org

### ISSUE THREAD

**Issue by donahchoo** [magit/forge#269] opened 2020-04-24 19:52 UTC
My repository recently switched orgs and now I can't open a PR anymore.  For better or worse, we aren't using forks.  I try to open a PR and I get this:

> Cannot use ‘forge-create-pullreq’ in "/Users/donahchoo/Developer/myprojects/" yet.
> Use `M-x forge-pull' before trying again.

When I try the pull I get:

>peculiar error: "UNIQUE constraint failed: repository.id"

I'm happy to work around this by using sqlite directly if that's possible....

**Comment by tarsius** [comment] 2020-04-25 22:08
Duplicate of #188, more or less.

**Closed** 2020-04-25 22:08 UTC
Labels: duplicate
