### ISSUE TITLE
Error retrieving forge topics (emacs 26.3)

### ISSUE THREAD

**Issue by flamingbear** [magit/forge#187] opened 2019-09-04 16:28 UTC
Originally I was getting an error very, very similar to #159 

both of these lines:
```
error in process filter: closql--oset: Wrong type argument: arrayp, forge-pullreq
error in process filter: Wrong type argument: arrayp, forge-pullreq
```
But trying to debug, I ran forge-reset-database so that I could get a cleaner stack trace.  After running that, I am getting the following error when I run forge-pull-notifications.

```
Debugger entered--Lisp error: (wrong-type-argument arrayp forge-github-repository)
  eieio--slot-name-index(forge-github-repository worktree)
  closql-oset(#<forge-github-repository forge-github-repository> worktree "/Users/savoie/.emacs.d/")
  eieio-oset--closql-oset(#f(compiled-function (obj slot value) "Do the work for the macro `oset'.\nFills in OBJ's SLOT with VALUE." #<bytecode 0x40911433>) #<forge-github-repository forge-github-repository> worktree "/Users/savoie/.emacs.d/")
  apply(eieio-oset--closql-oset #f(compiled-function (obj slot value) "Do the work for the macro `oset'.\nFills in OBJ's SLOT with VALUE." #<bytecode 0x40911433>) (#<forge-github-repository forge-github-repository> worktree "/Users/savoie/.emacs.d/"))
  eieio-oset(#<forge-github-repository forge-github-repository> worktree "/Users/savoie/.emacs.d/")
  #f(compiled-function (demand &optional remote) "Return the current forge repository.\n\nIf the `forge-buffer-repository' is non-nil, then return that.\nOtherwise if `forge-buffer-topic' is non-nil, then return the\nrepository for that.  Finally if both variables are nil, then\nreturn the forge repository corresponding to the current Git\nrepository, if any." #<bytecode 0x43a52345>)(stub)
  apply(#f(compiled-function (demand &optional remote) "Return the current forge repository.\n\nIf the `forge-buffer-repository' is non-nil, then return that.\nOtherwise if `forge-buffer-topic' is non-nil, then return the\nrepository for that.  Finally if both variables are nil, then\nreturn the forge repository corresponding to the current Git\nrepository, if any." #<bytecode 0x43a52345>) stub nil)
  forge-get-repository(stub)
  forge-pull-notifications()
  funcall-interactively(forge-pull-notifications)
  call-interactively(forge-pull-notifications record nil)
  command-execute(forge-pull-notifications record)
  counsel-M-x-action("forge-pull-notifications")
  ivy-call()
  ivy-read("M-x " [js--tmp-location localp ansi-color-apply-overlay-face epg-context-signers bbdb-maybe-update-display 0 -is-infix\? vc-git-stash-snapshot denied spaceline-info-mode-off-hook counsel-alias-expand magit-reflog-commit bbdb-current-record markdown-match-bold org-emphasis-regexp-components gnus-info-set-score tramp-gvfs-handle-copy-file clearfunsym gnus-agent-group-covered-p nnmail-fix-eudora-headers js--expression-in-sgml-indent-line sgml-syntax-propertize gnus-summary-recenter avl-tree--stack-store--cmacro cl-print--preprocess matched-string epc:net-have-input-p :examined -some\? vc-git-conflicted-files 0 jedi:-virtualenv-version firstname s-s \" gnus-tree-buffer $ SIGALRM scale \' nnoo-import-1 gnus-summary-catchup-from-here :contents org-babel-results-keyword request-list sgml-tag-name--cmacro cperl-load-font-lock-keywords-1 gnus-data-mark ident calendar-debug-sexp ...] :predicate #f(compiled-function (sym) #<bytecode 0x43a5b655>) :require-match t :history counsel-M-x-history :action counsel-M-x-action :sort t :keymap (keymap (67108908 . counsel--info-lookup-symbol) (67108910 . counsel-find-symbol)) :initial-input nil :caller counsel-M-x)
  counsel-M-x()
  funcall-interactively(counsel-M-x)
  call-interactively(counsel-M-x nil nil)
  command-execute(counsel-M-x)
```

I have recently updated to `GNU Emacs 26.3 (build 1, x86_64-apple-darwin18.2.0, NS appkit-1671.20 Version 10.14.3 (Build 18D109)) of 2019-09-02`
and eieio-core.el is 1.4 the version bundled with emacs .

Let me know if I can help any more.

Thanks
Matt

**Comment by tarsius** [comment] 2019-09-04 16:40
Uninstall `forge`, `ghub` and `closql`. Restart Emacs. Reinstall `forge` (which also installs the dependencies).

Duplicate of #159 and #187.

**Closed by tarsius** 2019-09-04 16:40 UTC
