### ISSUE TITLE
Github Enterprise configuration

### ISSUE THREAD

**Issue by guofei** [magit/forge#76] opened 2019-01-17 06:57 UTC
I use Github Enterprise instance and couldn’t pull github pullrequest.

My git config
```
[github]
	host = git.corp.mycompany.co.jp
[github "HOST"]
	user = myname
```

I get an error like this when I pull forge topics:
```
progn: Cannot determine forge repository.  git@git.corp.company.co.jp:org/rep.git isn't a forge url
```

It did not work even when I added config like the following
```
;; forge
(with-eval-after-load 'forge
  (push '("git.corp.mycompany.co.jp" "api.git.corp.mycompany.co.jp" "git.corp.mycompany.co.jp" forge-github-repository) forge-alist)
)
```

Before I added the configuration above, I can run forge options and got `progn: Cannot determine forge repository. git@git.corp.company.co.jp:org/rep.git isn't a forge url` error.

<img width="736" alt="image1" src="https://user-images.githubusercontent.com/737136/51427577-e5c4b480-1c3c-11e9-8149-51065a232393.png">

But after I added the configuration, I can't run forge options any more beacuse it disappeared from the list. 

<img width="729" alt="image2" src="https://user-images.githubusercontent.com/737136/51427584-f117e000-1c3c-11e9-8105-32d0f2c600f8.png">

**Comment by tarsius** [comment] 2019-01-17 15:15
You spelled the name of the company as `mycompany` in one case and in the other as just `company` in the other. Maybe you made a similar typo in your real configuration?

Once I had noticed and fixed that difference, I was no longer able to reproduce this issue.

Also the variable that `ghub` uses is named `ghub.host`, not `github.host`, but that doesn't matter because Forge doesn't use that variable either. So you have to check the value of `remote.origin.url` instead and make sure that *that* matches the `forge-alist` entry.

**Comment by guofei** [comment] 2019-01-19 14:14
Thank you for your reply. I don't think there is no typo in my real configuration.
I revised the description to be more clear. Please check that.

**Comment by tarsius** [comment] 2019-01-21 20:51
After I have done

``` emacs-lisp
(push '("git.corp.mycompany.co.jp" "api.git.corp.mycompany.co.jp"
        "git.corp.mycompany.co.jp" forge-github-repository)
      forge-alist)
```

this returns non-nil

``` emacs-lisp
(forge--split-url "git@git.corp.mycompany.co.jp/foo/bar.git")
```

Try if it does that for you too.  If that works (and I cannot think of
a reason why it wouldn't, then also do

``` emacs-lisp
(forge--split-url "the-real-url")
```

If that doesn't work, then I cannot think of another reason than a
typo in your configuration.

Closing for now because I think this is a configuration issue that I
cannot diagnose from a distance.  Feel free to comment if you have new
information though.

**Closed** 2019-01-21 20:52 UTC
Labels: support

**Comment by logc** [comment] 2019-08-22 09:06
For reference of others who might have this issue and cannot make it work by using the above snippet, I figured out that `"api.ghe.mycompany.net"` was **not** the right second item in the `forge-github-repository` list. 

In fact, the default endpoint where a GHE instance is listening for API calls is `"ghe.mycompany.net/api/v3"`, so you should put the following in your configuration:

```emacs-lisp
(push '("ghe.mycompany.net" "ghe.mycompany.net/api/v3"
          "ghe.mycompany.net" forge-github-repository)
        forge-alist)
```
