### ISSUE TITLE
Better way of overriding pull request template and values?

### ISSUE THREAD

**Issue by codygman** [magit/forge#209] opened 2019-10-24 22:27 UTC
I glanced over some of the issues including #185 and #70 but I couldn't piece together the answer. I'm currently just re-implementing `forge--prepare-post-buffer`.

```
(use-package forge
  :after magit
  :config
  (defun forge--prepare-post-buffer (filename &optional header source)
    (let ((file (magit-git-dir
		 (convert-standard-filename
		  (concat "magit/posts/" filename)))))
      (make-directory (file-name-directory file) t)
      (let ((prevbuf (current-buffer))
	    (resume (file-exists-p file))
	    (buf (find-file-noselect file)))
	(with-current-buffer buf
	  (forge-post-mode)
	  (when header
	    (magit-set-header-line-format header))
	  (setq forge--pre-post-buffer prevbuf)
	  (when resume
	    (forge--display-post-buffer buf)
	    (when (magit-read-char-case "A draft already exists.  " nil
		    (?r "[r]esume editing existing draft")
		    (?d "[d]iscard draft and start over" t))
	      (erase-buffer)
	      (setq resume nil)))
	  (when (and (not resume) (string-prefix-p "new" filename))
	    (let-alist (forge--topic-template
			(forge-get-repository t)
			(if source 'forge-pullreq 'forge-issue))
	      (if source
		  (progn
		    (goto-char (point-min))
		    ;; title of pr is first line
		    (insert-clubhouse-story-details)
		    (goto-char (point-max))
		    (evil-append-line 0)
		    (insert "\n\n")
		    )
		(goto-char (or .position (point-min)))))))
	buf)))

  )
```

**Comment by tarsius** [comment] 2019-10-25 09:02
I am aware that there are some issues with that feature. The implementation looks really strange and is in need of serious refactoring and a totally understand that for someone who not even wrote it it is even harder to deal with it than for myself.

Eventually I will get around to doing something about it. At the same time this is not really a deal breaker and some strange unnecessary characters that were inserted into the initial text can easily be removed by the user again. Its a bit annoying but manageable.

I am not sure how your above implementation differs. You might want to add an explanation beyond "this is my implementation". So this more or less makes this a duplicate of #185. Maybe it would make sense to add the above to $185 maybe not.

**Closed** 2019-10-25 09:02 UTC
Labels: duplicate
