### ISSUE TITLE
Commits not appearing for pull requests

### ISSUE THREAD

**Issue by m-cat** [magit/forge#134] opened 2019-04-05 10:58 UTC
I just fetched forge topics for maidsafe/rfcs from github for the first time. I noticed that commits appear for some pull requests but not for others:

https://www.dropbox.com/s/35fotxbn3fbq85e/Screen%20Shot%202019-04-05%20at%2012.52.26%20PM.png?dl=0

When I navigate to the pull request to see more details, there is a "Commits" section but it is empty:

https://www.dropbox.com/s/dq1q4q9ejy9lxrl/Screen%20Shot%202019-04-05%20at%2012.58.11%20PM.png?dl=0

This is a big regression because being able to check out the PR branch directly from this view is very useful, but it only works if I can see the commits.

**Comment by tarsius** [comment] 2019-04-05 11:54
> I just fetched forge topics for maidsafe/rfcs from github for the first time. I noticed that commits appear for some pull requests but not for others:

The commits in the range `<base>..<head>` are shown. If that range is empty because `<head>` (the pull-request branch) has already been merged into `<base>`, then nothing is shown.

> When I navigate to the pull request to see more details, there is a "Commits" section but it is empty:

I'll think about whether it makes sense to display already-merged commits here. Or rather how to accomplish that, not sure if Github exposes the necessary information and if so if we already fetch it.

> This is a big regression because being able to check out the PR branch directly from this view is very useful, but it only works if I can see the commits.

I don't think it is a regression but that this limitation always existed.

**Comment by m-cat** [comment] 2019-04-05 12:03
> The commits in the range <base>..<head> are shown. If that range is empty because <head> (the pull-request branch) has already been merged into <base>, then nothing is shown.

That explains why some of the other PRs in the screenshot weren't displaying commits (except for #286, which hasn't been merged). But although the PR in question (#294) is merged now, it wasn't merged at the time I wrote this Issue. If I'm understand correctly then it should have been displaying commits.

My workflow is to look at unmerged PRs with forge and check out the branch directly from the commit so I don't have to fetch the branch manually -- this was an unmerged PR so I was surprised it didn't work.

Btw, now that it has been merged, the "Commits" section no longer appears:
https://www.dropbox.com/s/ufj4s6fgep837ks/Screen%20Shot%202019-04-05%20at%201.57.01%20PM.png?dl=0
This behavior seems fine for me, whereas an empty "Commits" seems like a bug.

> I don't think it is a regression but that this limitation always existed.
I've never encountered this bug so I assumed it was introduced recently.

**Comment by tarsius** [comment] 2019-04-05 12:13
> it wasn't merged at the time I wrote this Issue. If I'm understand correctly then it should have been displaying commits.

Forge doesn't actually check whether the branch is merged before trying to insert the unmerged commits. I simply runs `git log <base>..<head>` and sees what happens. If the Github and Git data are out-of-sync, then surprising things can happen, which I guess is what happened. But it is hard to investigate this after the fact. If it ever happens again, try to leave things as they are so that we can investigate.

**Comment by m-cat** [comment] 2019-04-05 12:21
> But it is hard to investigate this after the fact.

#286 in the first screenshot has the exact same issue :). If you want to try and reproduce it, the repo is https://github.com/maidsafe/rfcs.

Thanks! 👍

**Comment by tarsius** [comment] 2019-04-05 12:31
Could you avoid fetching anything in that repository until I know what questions I have to ask you? (I won't get to this at least for a few more hours.)

**Comment by m-cat** [comment] 2019-04-05 12:34
Sure 👍

**Closed** 2019-06-18 12:00 UTC
Labels: bug

**Comment by nicu-chiciuc** [comment] 2020-09-19 10:18
I'm not sure if I'm doing something wrong, but it seems that I was able to fetch all the PR of my repository yet there aren't any commits showing. I've specifically checked PRs that are not merge yet
<img width="844" alt="Screen Shot 2020-09-19 at 13 13 29" src="https://user-images.githubusercontent.com/4076804/93664769-09777800-fa7a-11ea-9349-5f5465819a42.png">

I'm still new to emacs so I'll try to briefly explain all that I did to get to this point:
* Use emacs doom
* add `(magit +forge)` to `init.el`
* manually edit `.authinfo` (here I wasn't sure if the package name after the `^` should be `forge` or the name of my package, but it seems to work when it's set to `login nicu-chiciuc^forge`
* `M-x forge-pull`

I can provide additional info if needed

**Comment by m-cat** [comment] 2020-09-19 20:25
Probably best to start a new PR. My case was unconfirmed so I deleted the screenshots.

**Comment by tarsius** [comment] 2021-01-05 18:22
I figured out a likely cause, see https://github.com/magit/forge/issues/320#issuecomment-754812905.

**Comment by JasonMFry** [comment] 2021-09-30 15:33
> I figured out a likely cause, see [#320 (comment)](https://github.com/magit/forge/issues/320#issuecomment-754812905).

This was the solution for me, thanks!
