### ISSUE TITLE
error when updating changed remote URL

### ISSUE THREAD

**Issue by titaniumbones** [magit/forge#200] opened 2019-09-30 15:10 UTC
If I rename a remote Github repository and hten try to update the remote's url property, I get an emacsQL error: 

```
(emacsql-constraint "UNIQUE constraint failed: repository.id")
```

This is easily fixed by reverting the URL to the old value, which Github will forward for an indefinite period, but it seems like forge should make it possible to make these changes. 

Can you suggest a workaround?

Thanks @tarsius

**Comment by MatthewFluet** [comment] 2019-09-30 16:01
Duplicate of #188 (which suggests the workaround).

**Closed** 2019-09-30 16:03 UTC
Labels: duplicate
