### ISSUE TITLE
Spurious horizontal ruler inserted in pull request buffer

### ISSUE THREAD

**Issue by mboes** [magit/forge#263] opened 2020-04-05 19:48 UTC
When creating a pull request with a branch containing a single commit as the source branch, the PR description buffer is populated with text of the following form:

```
# Commit first line

commit body

---

#
```

Notice the spurious `---` at the bottom. This seems to come from https://github.com/magit/forge/blob/master/lisp/forge-post.el#L157. Notice also the spurious `#` at the bottom. Not sure where that's coming from.

I would expect that in the single commit case, the PR description buffer contains exactly the commit message of the commit.

**Comment by tarsius** [comment] 2020-04-05 19:52
Duplicate of #185.

**Closed** 2020-04-05 19:52 UTC
Labels: duplicate
