### ISSUE TITLE
In topics menu: cannot bind C-c C-n to forge-create-issue

### ISSUE THREAD

**Issue by ouboub** [magit/forge#724] opened 2024-11-08 09:37 UTC
I have the following setting in my init file
``` emacs-lisp
(defun my-issue-mode-keys ()
  (interactive)
  (local-set-key "\C-c\C-n" 'forge-create-issue))
(add-hook 'forge-issue-mode-hook 'my-issue-mode-keys)
(add-hook 'forge-topic-mode-hook 'my-issue-mode-keys)
```
I open a directory, which is a git repository added in forge's database.

I  run `forge-list-topics` enter the issues (which are in topic mode (see screenshot)
but `C-c C-n` is not bound to forge-create-issue, and 

- `where-is`
- `forge-create-issue`
returns nil.

what do I miss?
Uwe Brauer

**Comment by mattiasb** [comment] 2024-11-08 10:47
I believe this is a more general Emacs configuration issue and would be better asked on (for example) the `r/emacs` subreddit or somewhere else.

With that said, this might work out for you instead:
```lisp
(with-eval-after-load 'forge-topic
  (define-key 'forge-topic-mode-map "C-c C-n" #'forge-create-issue)
  (define-key 'forge-issue-mode-map "C-c C-n" #'forge-create-issue))
```

**Comment by ouboub** [comment] 2024-11-08 11:47
Thanks, but when I **eval** this expression, I obtain 
``` emacs-lisp

Debugger entered--Lisp error: (wrong-type-argument keymapp forge-topic-mode-map)
  define-key(forge-topic-mode-map "C-c C-n" forge-create-issue)
  (lambda nil (define-key 'forge-topic-mode-map "C-c C-n" #'forge-create-issue) (define-key 'forge-issue-mode-map "C-c C-n" #'forge-create-issue))()
  eval-after-load(forge-topic (lambda nil (define-key 'forge-topic-mode-map "C-c C-n" #'forge-create-issue) (define-key 'forge-issue-mode-map "C-c C-n" #'forge-create-issue)))
  eval((eval-after-load 'forge-topic #'(lambda nil (define-key 'forge-topic-mode-map "C-c C-n" #'forge-create-issue) (define-key 'forge-issue-mode-map "C-c C-n" #'forge-create-issue))) nil)
  elisp--eval-last-sexp(nil)
  eval-last-sexp(nil)
  funcall-interactively(eval-last-sexp nil)
  call-interactively(eval-last-sexp nil nil)
  command-execute(eval-last-sexp)
```

**Comment by ouboub** [comment] 2024-11-08 11:55
I also tried:
``` emacs-lisp
(with-eval-after-load 'forge-topic
  (define-key forge-topic-mode-map (kbd "C-c C-n") #'forge-create-issue)
  (define-key forge-issue-mode-map (kbd "C-c C-n") #'forge-create-issue))
```
but it does not work neither,

**Comment by mattiasb** [comment] 2024-11-08 12:46
I tested that exact code and it works here. I made a gist of the config [here](https://gist.github.com/mattiasb/17bf9836870ac1e97d3dc1c7734bd9cb).

I'll end my side of this conversation here based on my earlier note that this isn't an issue in Magit.

**Comment by tarsius** [comment] 2024-11-08 13:28
The parent keymaps were not set as intended. Just fixed in 9ac2afbbbc13e32cad878bb33f69e1fc36d9f94e.

```elisp
(with-eval-after-load 'forge-topic
  (define-key forge-topic-mode-map (kbd "C-c C-n") #'forge-create-issue)
  ;; Additionally you probably want:
  (define-key forge-topic-mode-map (kbd "C-c C-n") #'forge-create-pullreq))
```

**Comment by tarsius** [comment] 2024-11-08 13:36
However, since you said

> In topics menu:

(plural "topics"), and because that would make more sense, I am guessing what you actually want is

```elisp
(with-eval-after-load 'forge-topics
  (define-key forge-topics-mode-map (kbd "C-c C-n") #'forge-create-issue)
  (define-key forge-topics-mode-map (kbd "C-c C-p") #'forge-create-pullreq))
```

**Comment by ouboub** [comment] 2024-11-08 13:38
> The parent keymaps were not set as intended. Just fixed in [9ac2afb](https://github.com/magit/forge/commit/9ac2afbbbc13e32cad878bb33f69e1fc36d9f94e).
> 
> ```emacs-lisp
> (with-eval-after-load 'forge-topic
>   (define-key forge-topic-mode-map (kbd "C-c C-n") #'forge-create-issue)
>   ;; Additionally you probably want:
>   (define-key forge-topic-mode-map (kbd "C-c C-p") #'forge-create-pullreq))
> ```
> 
> Edit: Note that I just fixed the binding in the second binding.

I pulled and run make now I see
``` emacs-lisp
Compiling forge.el

In toplevel form:
forge.el:59:2: Error: Eager macro-expansion failure: (error "Need command, got ‘:info*’")
```

**Comment by tarsius** [comment] 2024-11-08 13:45
> I pulled and run make now I see

As I have pointed out in other issues you have opened, you **must** make **sure** that you are using an up-to-date version of `transient`. Since you mentioned that you pulled, I know that you are *trying* to do that, but are not successful.

An older version of `transient` is part of Emacs. (That version lacks support for `:info*`, thus you get this error.)

Since you apparently did not get that error before, I can only speculate that you now placed the above configuration somewhere very early in your init file. So early that it triggers **a** `transient` to be loaded, **before** the package manager was able to put the up-to-date separately installed `transient` on the `load-path`.

**Comment by ouboub** [comment] 2024-11-08 13:57
very odd
`locate-library` tells me 
`transient-20240821.158/` which is version **0.7.4**
and I can byte compiles the files within emacs, 
I presume I should run 
`make EMACS=/usr/local/bin/emacs -Q -l /home/oub/.emacs.d/elpa/transient-20240821.158/transistent.el'
or something like this

**Comment by tarsius** [comment] 2024-11-08 17:04
This is an issue with your local installation. I don't have the necessary insight into that, and also not the time, to help you with that. Sorry.

**Closed** 2024-11-08 17:04 UTC
Labels: support

**Comment by ouboub** [comment] 2024-11-08 19:07
I updated, transistent and forge via the package system.
then the code 
``` emacs-lisp
(with-eval-after-load 'forge-topics
  (define-key forge-topics-mode-map (kbd "C-c C-n") #'forge-create-issue)
  (define-key forge-topics-mode-map (kbd "C-c C-p") #'forge-create-pullreq))
```
so you can close this issue
